### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by taylorleprechaun** [CEN3031Q/TigerIsland#77]
A few lines from before and after an instance of the exception

```
SERVER: MAKE YOUR MOVE IN GAME B WITHIN 1.5 SECONDS: MOVE 19 PLACE ROCK+GRASS
CLIENT: GAME B MOVE 19 PLACE ROCK+GRASS AT 7 -6 -1 3 UNABLE TO BUILD
SERVER: GAME B MOVE 19 PLAYER 8 LOST: UNABLE TO BUILD
SERVER: GAME A MOVE 19 PLAYER 7 PLACED ROCK+GRASS AT -40 39 1 6 FOUNDED SETTLEMENT AT -41 40 1
SERVER: MAKE YOUR MOVE IN GAME A WITHIN 1.5 SECONDS: MOVE 19 PLACE ROCK+GRASS
CLIENT: GAME A MOVE 19 PLACE ROCK+GRASS AT 7 -8 1 4 FOUND SETTLEMENT AT -40 40 0
SERVER: GAME A MOVE 19 PLAYER 8 PLACED ROCK+GRASS AT 7 -8 1 4 FOUNDED SETTLEMENT AT -40 40 0
SERVER: GAME A MOVE 20 PLAYER 7 LOST: UNABLE TO BUILD
SERVER: GAME A OVER PLAYER 7 FORFEITED PLAYER 8 WIN
Exception in thread "Thread-129" java.util.ConcurrentModificationException
SERVER: GAME B OVER PLAYER 8 FORFEITED PLAYER 7 WIN
SERVER: END OF ROUND 1 OF 13 WAIT FOR NEXT MATCH
SERVER: BEGIN ROUND 2 OF 13
SERVER: NEW MATCH BEGINNING NOW YOUR OPPONENT IS PLAYER 5
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
	at Tournament.startNewRound(Tournament.java:25)
	at TournamentDriver.receiveInfo(TournamentDriver.java:48)
	at RoundProtocol.responseForMessage(RoundProtocol.java:39)
	at MessageDispatcher.processInput(MessageDispatcher.java:14)
	at WritingRunnable.run(WritingRunnable.java:18)
	at java.lang.Thread.run(Thread.java:745)
SERVER: MAKE YOUR MOVE IN GAME B WITHIN 1.5 SECONDS: MOVE 0 PLACE ROCK+ROCK
CLIENT: GAME B MOVE 0 PLACE ROCK+ROCK AT 2 0 -2 1 FOUND SETTLEMENT AT 0 -1 1
SERVER: GAME A MOVE 0 PLAYER 5 PLACED ROCK+ROCK AT -1 1 0 5 FOUNDED SETTLEMENT AT 0 1 -1
SERVER: GAME B MOVE 0 PLAYER 8 PLACED ROCK+ROCK AT 2 0 -2 1 FOUNDED SETTLEMENT AT 0 -1 1
SERVER: MAKE YOUR MOVE IN GAME A WITHIN 1.5 SECONDS: MOVE 0 PLACE JUNGLE+GRASS
```

**Comment by taylorleprechaun** [comment]
Another instance

```
SERVER: MAKE YOUR MOVE IN GAME B WITHIN 1.5 SECONDS: MOVE 4 PLACE GRASS+GRASS
CLIENT: GAME B MOVE 4 PLACE GRASS+GRASS AT 1 3 -4 1 EXPAND SETTLEMENT AT -4 2 2 ROCK
SERVER: GAME B MOVE 4 PLAYER 8 PLACED GRASS+GRASS AT 1 3 -4 1 EXPANDED SETTLEMENT AT -4 2 2 ROCK
SERVER: GAME B MOVE 4 PLAYER 5 FORFEITED: ILLEGAL TILE PLACEMENT
SERVER: GAME A OVER PLAYER 5 FORFEITED PLAYER 8 WIN
SERVER: GAME B OVER PLAYER 5 FORFEITED PLAYER 8 WIN
SERVER: END OF ROUND 2 OF 13 WAIT FOR NEXT MATCH
SERVER: BEGIN ROUND 3 OF 13
Exception in thread "Thread-159" java.util.ConcurrentModificationException
SERVER: NEW MATCH BEGINNING NOW YOUR OPPONENT IS PLAYER 3
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
	at Tournament.startNewRound(Tournament.java:25)
	at TournamentDriver.receiveInfo(TournamentDriver.java:48)
	at RoundProtocol.responseForMessage(RoundProtocol.java:39)
	at MessageDispatcher.processInput(MessageDispatcher.java:14)
	at WritingRunnable.run(WritingRunnable.java:18)
	at java.lang.Thread.run(Thread.java:745)
SERVER: MAKE YOUR MOVE IN GAME B WITHIN 1.5 SECONDS: MOVE 0 PLACE ROCK+ROCK
CLIENT: GAME B MOVE 0 PLACE ROCK+ROCK AT 2 0 -2 3 FOUND SETTLEMENT AT -1 0 1
SERVER: GAME A MOVE 0 PLAYER 3 PLACED ROCK+ROCK AT 0 -2 2 4 FOUNDED SETTLEMENT AT -1 -2 3
SERVER: GAME B MOVE 0 PLAYER 8 PLACED ROCK+ROCK AT 2 0 -2 3 FOUNDED SETTLEMENT AT -1 0 1
SERVER: MAKE YOUR MOVE IN GAME A WITHIN 1.5 SECONDS: MOVE 0 PLACE JUNGLE+GRASS
CLIENT: GAME A MOVE 0 PLACE JUNGLE+GRASS AT 2 0 -2 2 FOUND SETTLEMENT AT 0 -1 1
SERVER: GAME B MOVE 0 PLAYER 3 PLACED JUNGLE+GRASS AT 0 -2 2 4 FOUNDED SETTLEMENT AT -1 -2 3
```

**Comment by taylorleprechaun** [comment]
Another instance

```
SERVER: MAKE YOUR MOVE IN GAME B WITHIN 1.5 SECONDS: MOVE 17 PLACE JUNGLE+GRASS
CLIENT: GAME B MOVE 17 PLACE JUNGLE+GRASS AT 6 -5 -1 2 FOUND SETTLEMENT AT -3 4 -1
SERVER: GAME B MOVE 17 PLAYER 8 PLACED JUNGLE+GRASS AT 6 -5 -1 2 FOUNDED SETTLEMENT AT -3 4 -1
SERVER: GAME B MOVE 17 PLAYER 3 PLACED ROCK+LAKE AT 0 -36 36 4 FOUNDED SETTLEMENT AT -1 -36 37
SERVER: MAKE YOUR MOVE IN GAME B WITHIN 1.5 SECONDS: MOVE 18 PLACE LAKE+ROCK
CLIENT: GAME B MOVE 18 PLACE LAKE+ROCK AT -5 6 -1 1 UNABLE TO BUILD
SERVER: GAME B MOVE 18 PLAYER 8 LOST: UNABLE TO BUILD
SERVER: GAME A OVER PLAYER 8 FORFEITED PLAYER 3 WIN
SERVER: GAME B OVER PLAYER 8 FORFEITED PLAYER 3 WIN
Exception in thread "Thread-271" java.util.ConcurrentModificationException
SERVER: END OF ROUND 3 OF 13 WAIT FOR NEXT MATCH
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
SERVER: BEGIN ROUND 4 OF 13
	at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
	at Tournament.startNewRound(Tournament.java:25)
	at TournamentDriver.receiveInfo(TournamentDriver.java:48)
	at RoundProtocol.responseForMessage(RoundProtocol.java:39)
	at MessageDispatcher.processInput(MessageDispatcher.java:14)
	at WritingRunnable.run(WritingRunnable.java:18)
	at java.lang.Thread.run(Thread.java:745)
SERVER: END OF ROUND 4 OF 13 WAIT FOR NEXT MATCH
SERVER: BEGIN ROUND 5 OF 13
SERVER: NEW MATCH BEGINNING NOW YOUR OPPONENT IS PLAYER 16
SERVER: MAKE YOUR MOVE IN GAME B WITHIN 1.5 SECONDS: MOVE 0 PLACE ROCK+ROCK
CLIENT: GAME B MOVE 0 PLACE ROCK+ROCK AT 2 0 -2 6 FOUND SETTLEMENT AT 1 0 -1
SERVER: GAME A MOVE 0 PLAYER 16 PLACED ROCK+ROCK AT 1 -3 2 6 FOUNDED SETTLEMENT AT 0 1 -1
SERVER: GAME B MOVE 0 PLAYER 8 PLACED ROCK+ROCK AT 2 0 -2 6 FOUNDED SETTLEMENT AT 1 0 -1
SERVER: MAKE YOUR MOVE IN GAME A WITHIN 1.5 SECONDS: MOVE 0 PLACE JUNGLE+GRASS

```

**Comment by taylorleprechaun** [comment]
Final instance through end of log

```
CLIENT: GAME A MOVE 0 PLACE JUNGLE+GRASS AT 2 0 -2 6 FOUND SETTLEMENT AT 1 0 -1
SERVER: GAME B MOVE 1 PLAYER 16 FORFEITED: TIMEOUT
SERVER: GAME A MOVE 0 PLAYER 8 PLACED JUNGLE+GRASS AT 2 0 -2 6 FOUNDED SETTLEMENT AT 1 0 -1
SERVER: GAME A MOVE 2 PLAYER 16 FORFEITED: TIMEOUT
SERVER: GAME A OVER PLAYER 16 FORFEITED PLAYER 8 WIN
SERVER: GAME B OVER PLAYER 16 FORFEITED PLAYER 8 WIN
SERVER: END OF ROUND 5 OF 13 WAIT FOR NEXT MATCH
Exception in thread "Thread-285" java.util.ConcurrentModificationException
SERVER: BEGIN ROUND 6 OF 13
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
SERVER: NEW MATCH BEGINNING NOW YOUR OPPONENT IS PLAYER 10
	at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
	at Tournament.startNewRound(Tournament.java:25)
	at TournamentDriver.receiveInfo(TournamentDriver.java:48)
	at RoundProtocol.responseForMessage(RoundProtocol.java:39)
	at MessageDispatcher.processInput(MessageDispatcher.java:14)
	at WritingRunnable.run(WritingRunnable.java:18)
	at java.lang.Thread.run(Thread.java:745)
SERVER: MAKE YOUR MOVE IN GAME B WITHIN 1.5 SECONDS: MOVE 0 PLACE ROCK+ROCK
CLIENT: GAME B MOVE 0 PLACE ROCK+ROCK AT -1 2 -1 4 FOUND SETTLEMENT AT 0 -1 1
SERVER: GAME A MOVE 0 PLAYER 10 FORFEITED: TIMEOUT
SERVER: GAME B MOVE 0 PLAYER 8 PLACED ROCK+ROCK AT -1 2 -1 4 FOUNDED SETTLEMENT AT 0 -1 1
SERVER: GAME B MOVE 0 PLAYER 10 FORFEITED: TIMEOUT
SERVER: GAME A OVER PLAYER 10 FORFEITED PLAYER 8 WIN
SERVER: GAME B OVER PLAYER 10 FORFEITED PLAYER 8 WIN
SERVER: END OF ROUND 6 OF 13 WAIT FOR NEXT MATCH
SERVER: BEGIN ROUND 7 OF 13
SERVER: NEW MATCH BEGINNING NOW YOUR OPPONENT IS PLAYER 1
SERVER: MAKE YOUR MOVE IN GAME B WITHIN 1.5 SECONDS: MOVE 0 PLACE ROCK+ROCK
CLIENT: GAME B MOVE 0 PLACE ROCK+ROCK AT 0 2 -2 5 FOUND SETTLEMENT AT 0 -1 1
SERVER: GAME A MOVE 0 PLAYER 1 FORFEITED: TIMEOUT
SERVER: GAME B MOVE 0 PLAYER 8 PLACED ROCK+ROCK AT 0 2 -2 5 FOUNDED SETTLEMENT AT 0 -1 1
SERVER: GAME B MOVE 0 PLAYER 1 FORFEITED: TIMEOUT
```

**Comment by gonzalonunez** [comment]
Ok this is **awesome**. I'll be able to debug this at some point today I think and we should have it all fixed. One of the errors seems identical to one we just fixed.

**Comment by gonzalonunez** [comment]
@taylorleprechaun Ok, here's the fix. We need to change [this method](https://github.com/CEN3031Q/TigerIsland/blob/master/src/Tournament.java#L22) to:

```java
synchronized(players) {
    Iterator<String> iter = players.iterator();
    while (iter.hasNext()) {
        iter.remove();
    }
}
```

The problem occurs because we use a `for : each` loop. Can you make these changes whenever?

See [this](http://stackoverflow.com/questions/18448671/how-to-avoid-concurrentmodificationexception-while-removing-elements-from-arr) and [this](http://stackoverflow.com/questions/1066589/iterate-through-a-hashmap) for more.

**Comment by hsuj** [comment]
Looks like that code would work if `players` was an ArrayList object. But here's the Hashmap version according to [this Stackoverflow post](http://stackoverflow.com/questions/602636/concurrentmodificationexception-and-a-hashmap):

```
    public void startNewRound(String rid, String rounds) {
        synchronized (players) {
            Iterator iter = players.entrySet().iterator();

            while (iter.hasNext()) {
                Entry item = iter.next(); //importation issue with Entry
                iter.remove();
            }
        }
    }
```

But I'm having issues importing the correct library for the Entry type. So I don't know if we need it or if we can leave it out since I don't see `Entry item` using method calls. 

Another suggestion is to change `final private HashMap<String, Player> players = new HashMap<>();` to `final private ConcurrentHashMap<String, Player> players = new HashMap<>();` according to the second answer to that Stackoverflow post.

**Comment by gonzalonunez** [comment]
Sorry, forgot to add `entrySet()`. We don't need to actually grab a reference to the Entry, so if you can make the changes but without grabbing a reference via `next()` that'd be great.

**Comment by gonzalonunez** [comment]
Fixed. Good catch fam.
